services:
  app:
    build: .
    container_name: streamlit_app
    ports:
      - "8501:8501"
    depends_on:
      ollama:
        condition: service_started
    environment:
      OLLAMA_URL: http://ollama:11434
      HEALTH_WORKOUT_FILE: data/workouts.csv
      HEALTH_RECORD_FILE: data/records_data.csv
    restart: unless-stopped
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 4G
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    restart: unless-stopped
    entrypoint: ["/bin/sh", "-c"]
    command: >
      "ollama serve & 
       sleep 5 &&
       ollama pull llama3.2:1b &&
       wait"


volumes:
  ollama_data: